on:
  - push
jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build . -t mypythonapp
      - uses: Azure/container-scan@v0
        id: container-scan
        continue-on-error: true
        with:
          image-name: containerscandemo.azurecr.io/mypythonapp
      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push containerscandemo.azurecr.io/mypythonapp
      - name: Run ACR scan
        uses: azure/container-scan@v0.1.0
        with:
          registry: containerscandemo.azurecr.io
          image: mypythonapp:mypythonapp:latest
          severity: High
          fail-on: High
          token: ${{ secrets.AZURE_CREDENTIALS }}
    jobs:
      asc-scan:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Azure Login
            uses: azure/login@v1
            with: null
            creds: ${{ secrets.AZURE_CREDENTIALS }}
          - name: Run ASC scan
            uses: Azure/security-center@v1
            with:
              auto-discover: true
              scan: true
