on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t mypythonapp
      
    - uses: Azure/container-scan@v0
      id: container-scan
      continue-on-error: true
      with:
        image-name: mypythonapp
    
    - uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/mypythonapp:${{ github.run_number }}
    
    - name: Scan image
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ secrets.ACR_LOGIN_SERVER }}/mypythonapp
        severity-thr	eshold: CRITICAL
        run-quality-checks: true
    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/mypythonapp:${{ github.run_number }}
